version: "3"
services:
    graphite:
      image: graphiteapp/graphite-statsd
      hostname: graphite
      ports:
        - "80:80"
      volumes:
        - "./graphite/conf:/opt/graphite/conf"
        - "./data:/opt/graphite/storage"
      restart: unless-stopped
      environment:
        - GRAPHITE_TIME_ZONE=America/Chicago
    write-graphite:
      build: ./write-graphite
      restart: unless-stopped
      depends_on:
        - graphite

