version: "3"
services:
    graphite:
      image: graphiteapp/graphite-statsd
      hostname: graphite
      ports:
        - "8080:80"
      volumes:
        - "./graphite/conf:/opt/graphite/conf"
        - "~/graphite-storage:/opt/graphite/storage"
      restart: always

