version: "3"
services:
    graphite:
      image: graphiteapp/graphite-statsd
      hostname: graphite
      ports:
        - "8080:80"
        - "2003:2003"
      volumes:
        - "./graphite/conf:/opt/graphite/conf"
        - "./data:/opt/graphite/storage"
      restart: unless-stopped
    write-graphite:
      build: ./write-graphite
      restart: unless-stopped
      depends_on:
        - graphite

